### ISSUE TITLE
Do you have any roadmap for this module?

### ISSUE THREAD

**Issue by bitliner** [revolunet/spreadsheet-to-json#2]
I though about other features like:

* streaming (in case of very large spreadsheet)
* conversion to specific type (boolean, integer, etc.) for each cell
* access of sheets by integer instead of name

Do you plan anything similar for this module? 

I find it one of the best to read from Google Spreadsheet, and I was also thinking about a browser usage of Google Spreadsheet API to use Google Spreadsheet as a database (of course not comparable to databases like mysql, mongodb, etc.).

**Comment by revolunet** [comment]
Hi @bitliner 

I dont have any roadmap because it does what i need but new contributors are welcome !

Cell conversion is included, see the `formatCell` function
Browser version would be awesome
Sheet by integer should be trivial to implement

Have a good one

Ju
