### ISSUE TITLE
TypeError: extractSheets is not a function

### ISSUE THREAD

**Issue by tatianafrank** [revolunet/spreadsheet-to-json#5]
I am following the example in the docs using my own credentials and google doc ID and I am getting this error: TypeError: extractSheets is not a function

**Comment by tatianafrank** [comment]
Never mind, I looked at the code and the issue is with your example code not the code itself. You should update the example to extractSheets.extractSheets(..); You should change the name you're using for the module import to avoid confusion.

**Comment by revolunet** [comment]
thanks a lot for reporting 👍 i just fixed the example, hope this is now ok ?

**Comment by tatianafrank** [comment]
Hey this was my bad. It works with the format you used I just didn't notice that you imported using const { extractSheets } = require('spreadsheet-to-json'); format. I'm having a separate issue now though that I just logged separately.

**Comment by revolunet** [comment]
i fixed the example once you reported the issue :)
