### ISSUE TITLE
Returns null

### ISSUE THREAD

**Issue by tatianafrank** [revolunet/spreadsheet-to-json#6]
Using the format in the example. No errors but I just get null from the returned object when running extractSheets function.

**Comment by tatianafrank** [comment]
`extractSheets({
    spreadsheetKey: '1aBXlyvImhaQZGZRiFBflc137nO2h9N6pBIraQ09E0ew',
    credentials : false,
    sheetsToExtract: []
}, function(data) {
    console.log(data);
});`

That's the test code ^ The sheet is public and published to web.

**Comment by tatianafrank** [comment]
I set credentials to false because when I omit the credentials parameter I get `Error: No key or keyFile set.`

**Comment by tatianafrank** [comment]
Ok I think this is the issue: https://github.com/revolunet/spreadsheet-to-json/blob/master/src/index.js#L78

When I have the function return two objects instead of one then the second object contains the data and the first one contains null. So I think you need to up date the example in the docs to:

function(nullObject, data) {
    console.log('Customers: ', data.Customers);
    console.log('Invoices: ', data.Invoices);
});

**Comment by revolunet** [comment]
My bad, sorry for the misleading example :/

indeed this lib use the NodeJS "convention" where error is the first argument to the callback

thanks again for reporting and helping make the doc better !
