### ISSUE TITLE
Header symbol parsing issue

### ISSUE THREAD

**Issue by tatianafrank** [revolunet/spreadsheet-to-json#7]
When a colon (:) or slash (/) is present in the first row of a sheet, the value for the column containing the symbol is null. Oddly only the value comes back null but the field name itself containing the symbol displays correctly.

**Comment by tatianafrank** [comment]
I think you can resolve the issue by adjusting this line: 
https://github.com/revolunet/spreadsheet-to-json/blob/master/dist/index.js#L22 
to:
`return title.toLowerCase().replace(/[ #_/:]/gi, '');`

**Comment by revolunet** [comment]
Hi, I started to work on this but it broke some tests so I have to dig deeper. Will submit a fix next week hopefully

**Comment by revolunet** [comment]
Btw if you have a fix, PRs are welcome

**Comment by revolunet** [comment]
Hi, please check if this solves your issue : https://github.com/revolunet/spreadsheet-to-json/pull/9

made some housekeeping and removed babel and thus the mandatory build step

**Comment by tatianafrank** [comment]
Thanks! Looks like that did the trick!

**Comment by revolunet** [comment]
Ok thanks, published in @1.3.1
